#!/bin/bash




for instance in worker-0 worker-1 worker-2; do
    kubectl config set-cluster kubernetes-the-hard-wayws \
	      --certificate-authority=ca.pem \
	      --embed-certs=true \
	      --server=https:apiserver:6443 \
	      --kubeconfig=${instance}.kubeconfig

    kubectl config set-credentials system:node:${instance} \
	      --client-certificate=${instance}.pem \
	      --client-key=${instance}-key.pem \
	      --embed-certs=true \
	      --kubeconfig=${instance}.kubeconfig

    kubectl config set-context default \
	      --cluster=kubernetes-the-hard-wayws \
	      --user=system:node:${instance} \
	      --kubeconfig=${instance}.kubeconfig

    kubectl config use-context default --kubeconfig=${instance}.kubeconfig
done
