---
Description: Sets up compute infrasructure for Kubernetes

Parameters:
  AvailabilityZone:
    Type: String
    Default: us-west-2c

  AmiId:
    Type : AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: "/aws/service/ami-amazon-linux-latest/amzn2-ami-minimal-hvm-arm64-ebs"

  InstanceType:
    Type: String
    Default: a1.medium

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      EnableDnsHostnames: true
      EnableDnsSupport: true
      CidrBlock: 10.240.0.0/16
      Tags: [{Key: "Name", Value: "k8s-arm"}]

Resources:
  RootCA:
    Type: 'AWS::ACMPCA::CertificateAuthority'
    Properties:
      Tags: [{Key: "Name", Value: "k8s-arm"}]
      Type: ROOT
      KeyAlgorithm: RSA_2048
      SigningAlgorithm: SHA256WITHRSA
      Subject:
        Country: US
        Organization: Kubernetes
        OrganizationalUnit: CA
        State: WA
      RevocationConfiguration:
        CrlConfiguration:
          Enabled: false

  RootCACertificate:
    Type: 'AWS::ACMPCA::Certificate'
    Properties:
      CertificateAuthorityArn: !Ref RootCA
      CertificateSigningRequest: !GetAtt 
        - RootCA
        - CertificateSigningRequest
      SigningAlgorithm: SHA256WITHRSA
      TemplateArn: 'arn:aws:acm-pca:::template/RootCACertificate/V1'
      Validity:
        Type: DAYS
        Value: 100

  RootCAActivation:
    Type: 'AWS::ACMPCA::CertificateAuthorityActivation'
    Properties:
      CertificateAuthorityArn: !Ref RootCA
      Certificate: !GetAtt 
        - RootCACertificate
        - Certificate
      Status: ACTIVE
 
