#!/bin/bash

set -efuo pipefail

source_dir=$1
dest_dir=$2
yaml_file=$3
shift 3				# "$@" is dirs to search for .missing

rm -rf $dest_dir
mkdir -p $dest_dir

rsync -tr $source_dir/ $dest_dir

# Replace all the files that need mustache substitutions
while read -r file
do
    echo $file
    generated_file=${file%.*}
    mustache $yaml_file $file > $generated_file
    if cmp -s $generated_file $file
    then
	echo 1>&2 "$generated_file didn't change from $file, substitution must have failed:"
	grep 1>&2 -F "{{" $file
	exit 1
    fi
      
    cat $generated_file		# XXX remove
    rm $file
done < <(find $dest_dir -type f -name \*.mustache)

set -x

# Replace all missing files with the real ones
while read -r missing_path
do
    echo $missing_path
    missing=$(basename $missing_path)
    desired_path=${missing_path%.*}
    if replacement=$(find "$@" -name "${missing%.*}" | head -1)
    then
	cp $replacement $desired_path
	rm $missing_path
    else
	echo 1>&2 "Unable to find replacement for '$missing_path' in '$missing_files_dir'"
	ls $missing_files_dir
	exit 2
    fi
done < <(find $dest_dir -type f -name \*.missing)

exit

